name: Auto Merge

on:
  check_suite:
    types:
      - completed
  pull_request:
    branches:
      - master
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-18.04
    steps:
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.8.4
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "auto-merge,!protected"
          MERGE_METHOD: "merge"
          MERGE_RETRIES: "6"
