name: Webhook Pipeline

on:
  pull_request:
    branches:
      - master
    paths:
      - 'aws-github-webhook/**'
    types: [closed]

jobs:
  webhook-pipeline:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Cache Node dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Node dependencies
        run: yarn install --no-progress --non-interactive

      - name: Build AWS GitHub webhook infrastructure
        run: yarn workspace aws-github-webhook build

      - name: Deploy AWS GitHub webhook infrastructure
        run: yarn workspace aws-github-webhook deploy --no-staging --require-approval never

      - name: Create GitHub Webhook
        uses: actions/github-script@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createWebhook({
              active: true,
              config: {
                url: "https://a6bnu0x0qh.execute-api.eu-west-2.amazonaws.com/prod/github",
              },
              events: ["push"],
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
